In [1]:
import torch
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# Set default to run on the GPU if available (for the speed up)
if torch.cuda.is_available():
    torch.cuda.set_device(device)
torch.set_default_tensor_type('torch.cuda.FloatTensor')


from torch.utils.data import Dataset, DataLoader, random_split

As a first step we prepare the data. We will do this with the help of keras (because it has done a lot of the heavy lifting for us) 

In [2]:
import tensorflow.keras.datasets.imdb as imdb

In [59]:
### we use a dataset, but we cheat a little by using keras
import torch

maxlen = 250
num_words = 2500
class ImdbDatasetTrain(Dataset):
    
    '''
    Datasets needs an __init__, __get_item__ and __len__
    '''
    
    def __init__(self):
        self.samples = []
        (x_train, y_train), (x_test, y_test) = imdb.load_data(skip_top=10, num_words=num_words, oov_char=2, maxlen=maxlen)

        x_train = [x + [0] * (maxlen- len(x)) for x in x_train]
        
        
        for x, y in zip(x_train, y_train):
            self.samples.append((torch.LongTensor(x).to(device), y))

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        return self.samples[idx]
    

In [60]:
dataset = ImdbDatasetTrain()
dataloader = DataLoader(dataset, batch_size=64, shuffle=True, )

In [61]:
for i, (review, cat) in enumerate(dataloader):
    print(review)

tensor([[  2,   2, 261,  ...,   0,   0,   0],
        [  2,  14,  20,  ...,   0,   0,   0],
        [  2,  48,  25,  ...,   0,   0,   0],
        ...,
        [  2,  14,  22,  ...,   0,   0,   0],
        [  2,  48,  25,  ...,   0,   0,   0],
        [  2,  14,   2,  ...,   0,   0,   0]])
tensor([[  2,  48, 874,  ...,   0,   0,   0],
        [  2,  13, 566,  ...,   0,   0,   0],
        [  2,  13,  16,  ...,   0,   0,   0],
        ...,
        [  2,   2, 146,  ...,   0,   0,   0],
        [  2,  11, 661,  ...,   0,   0,   0],
        [  2,  14,  20,  ...,   0,   0,   0]])
tensor([[  2,   2,  65,  ...,   0,   0,   0],
        [  2,  14, 431,  ...,   0,   0,   0],
        [  2,  14,  22,  ...,   0,   0,   0],
        ...,
        [  2, 307,  22,  ...,   0,   0,   0],
        [  2,  14,  22,  ...,   0,   0,   0],
        [  2,  13,  16,  ...,   0,   0,   0]])
tensor([[  2,   2, 954,  ...,   0,   0,   0],
        [  2,  48,  25,  ...,   0,   0,   0],
        [  2,  50,   2,  ...,   0,   0

tensor([[   2,    2,  775,  ...,    0,    0,    0],
        [   2, 2145,    2,  ...,    0,    0,    0],
        [   2,   14,    2,  ...,    0,    0,    0],
        ...,
        [   2,   14,   16,  ...,    0,    0,    0],
        [   2,   14,   20,  ...,    0,    0,    0],
        [   2,   14,   20,  ...,    0,    0,    0]])
tensor([[  2,   2,  39,  ...,   0,   0,   0],
        [  2,  14,  20,  ...,   0,   0,   0],
        [  2,  14,  20,  ...,   0,   0,   0],
        ...,
        [  2,  14,  16,  ...,   0,   0,   0],
        [  2,  14, 374,  ...,   0,   0,   0],
        [  2,  14, 117,  ...,   0,   0,   0]])
tensor([[  2,  39,   2,  ...,   0,   0,   0],
        [  2,  12,  16,  ...,   0,   0,   0],
        [  2,  96,   2,  ...,   0,   0,   0],
        ...,
        [  2, 261,   2,  ...,   0,   0,   0],
        [  2,  19,   2,  ...,   0,   0,   0],
        [  2,  18, 783,  ...,   0,   0,   0]])
tensor([[  2,   2, 301,  ...,   0,   0,   0],
        [  2,  48,  25,  ...,   0,   0,   0],
  

tensor([[   2,   32,   13,  ...,    0,    0,    0],
        [   2,   14,    2,  ...,    0,    0,    0],
        [   2,   51,    2,  ...,    0,    0,    0],
        ...,
        [   2, 1318, 1318,  ...,    0,    0,    0],
        [   2,   14,    2,  ...,    0,    0,    0],
        [   2,   13,  447,  ...,    0,    0,    0]])
tensor([[   2,   14,   20,  ...,    0,    0,    0],
        [   2,  894, 1843,  ...,    0,    0,    0],
        [   2,   13, 1033,  ...,    0,    0,    0],
        ...,
        [   2, 2476, 1782,  ...,    0,    0,    0],
        [   2,    2,  464,  ...,    0,    0,    0],
        [   2,    2,    2,  ...,    0,    0,    0]])
tensor([[  2,  13,  70,  ...,   0,   0,   0],
        [  2,  13, 377,  ...,   0,   0,   0],
        [  2,  13, 358,  ...,   0,   0,   0],
        ...,
        [  2,  13,  86,  ...,   0,   0,   0],
        [  2,  13,  16,  ...,   0,   0,   0],
        [  2,  13, 858,  ...,   0,   0,   0]])
tensor([[   2,   14,   20,  ...,    0,    0,    0],
      

tensor([[  2,   2,  89,  ...,   0,   0,   0],
        [  2,  13,  43,  ...,   0,   0,   0],
        [  2,  24,  60,  ...,   0,   0,   0],
        ...,
        [  2,   2, 950,  ...,   0,   0,   0],
        [  2,  12,   2,  ...,   0,   0,   0],
        [  2,   2,  20,  ...,   0,   0,   0]])
tensor([[  2, 637, 202,  ...,   0,   0,   0],
        [  2,  10,  10,  ...,   0,   0,   0],
        [  2, 261,  50,  ...,   0,   0,   0],
        ...,
        [  2,  14,  20,  ...,   0,   0,   0],
        [  2,  14,  16,  ...,   0,   0,   0],
        [  2,   2, 192,  ...,   0,   0,   0]])
tensor([[   2,  149,   14,  ...,    0,    0,    0],
        [   2,   13, 1562,  ...,    0,    0,    0],
        [   2,   14,    2,  ...,    0,    0,    0],
        ...,
        [   2,   14,   47,  ...,    0,    0,    0],
        [   2,   24,   15,  ...,    0,    0,    0],
        [   2,   14,   16,  ...,    0,    0,    0]])
tensor([[   2, 1713,   28,  ...,    0,    0,    0],
        [   2,   14,   22,  ...,    0,    

tensor([[  2,  13,  16,  ...,   0,   0,   0],
        [  2,  13,  28,  ...,   0,   0,   0],
        [  2, 608,  13,  ...,   0,   0,   0],
        ...,
        [  2,  14,  22,  ...,   0,   0,   0],
        [  2,   2,   2,  ...,   0,   0,   0],
        [  2,  51,  70,  ...,   0,   0,   0]])
tensor([[  2,  73, 637,  ...,   0,   0,   0],
        [  2,   2,  52,  ...,   0,   0,   0],
        [  2,  14,  47,  ...,   0,   0,   0],
        ...,
        [  2,   2,  47,  ...,   0,   0,   0],
        [  2,  14, 582,  ...,   0,   0,   0],
        [  2,  13, 115,  ...,   0,   0,   0]])
tensor([[  2, 151,  13,  ...,   0,   0,   0],
        [  2,  14,   2,  ...,   0,   0,   0],
        [  2,  14,  22,  ...,   0,   0,   0],
        ...,
        [  2,  14, 123,  ...,   0,   0,   0],
        [  2, 111, 504,  ...,   2,   0,   0],
        [  2, 149, 159,  ...,   0,   0,   0]])
tensor([[  2,  34,  49,  ...,   0,   0,   0],
        [  2,   2,   2,  ...,   0,   0,   0],
        [  2,  13, 188,  ...,   0,   0

tensor([[   2, 1276,   13,  ...,    0,    0,    0],
        [   2,   18,   27,  ...,    0,    0,    0],
        [   2,   14,    2,  ...,    0,    0,    0],
        ...,
        [   2,  422,   49,  ...,    0,    0,    0],
        [   2,  146,   24,  ...,    0,    0,    0],
        [   2, 1505,    2,  ...,    0,    0,    0]])
tensor([[   2,    2, 1352,  ...,    0,    0,    0],
        [   2,   13,   66,  ...,    0,    0,    0],
        [   2,  151,    2,  ...,    0,    0,    0],
        ...,
        [   2,   13,  423,  ...,    0,    0,    0],
        [   2,    2,   20,  ...,    0,    0,    0],
        [   2,   13,  219,  ...,    0,    0,    0]])
tensor([[  2,  14, 641,  ...,   0,   0,   0],
        [  2,  43, 385,  ...,   0,   0,   0],
        [  2,  13, 119,  ...,   0,   0,   0],
        ...,
        [  2,   2,   2,  ...,   0,   0,   0],
        [  2,  14,   2,  ...,   0,   0,   0],
        [  2,  61,   2,  ...,   0,   0,   0]])
tensor([[ 2, 14,  2,  ...,  0,  0,  0],
        [ 2, 14,  

In [62]:
#Next we need to create 

In [76]:
import torch.nn as nn 
from torch.nn import functional as F
n_hidden = 128


class LSTMModel(nn.Module):

    def __init__(self, num_words, n_hidden):
        super(LSTMModel, self).__init__()
        self.embedding = nn.Embedding(num_words, n_hidden)
        self.LSTM = nn.LSTM(n_hidden, n_hidden, batch_first=True,)
        self.fc = nn.Linear(n_hidden, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, review):
        
        x = self.embedding(review)
        
        rnn_out, _ = self.LSTM(x)
     
        fc_out = self.fc(rnn_out[:, -1 ]) # Only need the last output of the rnn
        
        return fc_out
        
    
model = LSTMModel(num_words + 2, n_hidden)
model.to(device)

LSTMModel(
  (embedding): Embedding(2502, 128)
  (LSTM): LSTM(128, 128, batch_first=True)
  (fc): Linear(in_features=128, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [77]:
import torch
lr=0.01

criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=lr)
n_epochs = 50

In [78]:
loss_history = []
test_history = []
acc_history = []
n_epochs = 20
for epoch in range(1, n_epochs + 1):
    epoch_total_loss = 0
    for i, (review, cat) in enumerate(dataloader):

        optimizer.zero_grad() # Clears existing gradients from previous epoch
        output = model(review)

  
        loss = criterion(output, cat.float().view(-1, 1))
        loss.backward() # Does backpropagation and calculates gradients
        optimizer.step() # Updates the weights accordingly

        epoch_total_loss += loss.item() # Keep track of the total loss
    loss_history.append(epoch_total_loss/len(dataloader))


    print('Epoch: {}/{}.............'.format(epoch, n_epochs), end=' ')
    print("Loss: {:.4f}".format(epoch_total_loss/ len(dataloader)))

Epoch: 1/20............. Loss: 0.6955
Epoch: 2/20............. Loss: 0.6936
Epoch: 3/20............. Loss: 0.6935
Epoch: 4/20............. Loss: 0.6932
Epoch: 5/20............. Loss: 0.6794
Epoch: 6/20............. Loss: 0.6178
Epoch: 7/20............. Loss: 0.5409
Epoch: 8/20............. Loss: 0.4607
Epoch: 9/20............. Loss: 0.4105
Epoch: 10/20............. Loss: 0.3848
Epoch: 11/20............. Loss: 0.3598
Epoch: 12/20............. Loss: 0.3371
Epoch: 13/20............. Loss: 0.3244
Epoch: 14/20............. Loss: 0.3080
Epoch: 15/20............. Loss: 0.2994
Epoch: 16/20............. Loss: 0.2903
Epoch: 17/20............. Loss: 0.2795
Epoch: 18/20............. Loss: 0.2714
Epoch: 19/20............. Loss: 0.2639
Epoch: 20/20............. Loss: 0.2549
